### ISSUE TITLE
[BUG] 我不确定这是哪里出现了问题

### ISSUE THREAD

**Issue by ZhangMouQWQ** [Rothes/PrismRefracted#2]
插件在加载时会大量刷屏式的提示 
[Prism] 缺少本地化语言: [某个模组物品ID]
而且需要待其完全把所有模组物品都遍历一遍之后才正常
每次重启服务端都会这样
插件版本:Prism v3.6.1-CN-b1.jar
服务端核心:mohist-1.16.5-1086-server.jar
启用了 MYSQL数据库 并正常连接
(亦或者这个插件它本身就是这样?)

**Comment by Rothes** [comment]
待改进

**Comment by ZhangMouQWQ** [comment]
> 待改进

很期待改进后的成果 :D

**Comment by Rothes** [comment]
由于物品翻译只含有原版内容，不含模组翻译，所以每一个模组项目都会提示缺少本地化语言。
之后会限制显示数量。

**Comment by Rothes** [comment]
已解决：https://github.com/Rothes/PrismRefracted/commit/d90c77d9573ffa96276256345b08dfcdcbfd0653
请更新插件。

**Comment by ZhangMouQWQ** [comment]
> 已解决：[d90c77d](https://github.com/Rothes/PrismRefracted/commit/d90c77d9573ffa96276256345b08dfcdcbfd0653) 请更新插件。

很遗憾
在Prism v3.6.1-CN-b2版本上
确实不会出现缺少本地化文件
取而代之的是
Registry (模组名):(物品名): Object did not get ID it asked for. Name: 
模组ID类名 Expected: XXX Got: XXX    #X为随机数
如果你需要相关完全体
我可以提供

**Comment by Rothes** [comment]
> > 已解决：[d90c77d](https://github.com/Rothes/PrismRefracted/commit/d90c77d9573ffa96276256345b08dfcdcbfd0653) 请更新插件。
> 
> 很遗憾 在Prism v3.6.1-CN-b2版本上 确实不会出现缺少本地化文件 取而代之的是 Registry (模组名):(物品名): Object did not get ID it asked for. Name: 模组ID类名 Expected: XXX Got: XXX #X为随机数 如果你需要相关完全体 我可以提供

可加入群 422532220 详细讨论, 或开启另一个 issue.
Mohist 兼容性一直有很大问题, 1.16 建议使用 CatServer 端.

**Comment by ZhangMouQWQ** [comment]
> > > 已解决：[d90c77d](https://github.com/Rothes/PrismRefracted/commit/d90c77d9573ffa96276256345b08dfcdcbfd0653) 请更新插件。
> > 
> > 
> > 很遗憾 在Prism v3.6.1-CN-b2版本上 确实不会出现缺少本地化文件 取而代之的是 Registry (模组名):(物品名): Object did not get ID it asked for. Name: 模组ID类名 Expected: XXX Got: XXX #X为随机数 如果你需要相关完全体 我可以提供
> 
> 可加入群 422532220 详细讨论, 或开启另一个 issue. Mohist 兼容性一直有很大问题, 1.16 建议使用 CatServer 端.

或许你说的对,稍后我会更换到其服务端核心再做尝试
如果还是会出现此类情况我会新建一个issue
