### ISSUE TITLE
[BUG] 好吧,还是那个问题,但这次它无关紧要?(?虽然,可能,但是?)

### ISSUE THREAD

**Issue by ZhangMouQWQ** [Rothes/PrismRefracted#3]
![image](https://user-images.githubusercontent.com/106049042/200583303-adb6bb8d-6dee-4fcf-a6b3-4798dad91f31.png)
![image](https://user-images.githubusercontent.com/106049042/200583345-ad2f8ef0-f027-4cd8-9a46-b51d94395fc4.png)

**Comment by ZhangMouQWQ** [comment]
我无法直接表述这个问题
故直接贴入截图
:D

**Comment by ZhangMouQWQ** [comment]
服务端已经切换到
CatServer-1.16.5-a76056a9-server.jar
(最新版本)

**Comment by Rothes** [comment]
由于插件中内置的翻译表只包含原版内容的翻译, 故所有模组内容都会提示缺少本地化语言.
目前没有工具能合并模组中的本地化到Prism内置的翻译表中.

**Comment by ZhangMouQWQ** [comment]
> 由于插件中内置的翻译表只包含原版内容的翻译, 故所有模组内容都会提示缺少本地化语言. 目前没有工具能合并模组中的本地化到Prism内置的翻译表中.
> 
> 这些内容会以英文的形式被查询到.

但这次其遍历时将其压缩至一起
启动时间有所加快
因此如标题那样
可能是无关紧要的?

**Comment by Rothes** [comment]
> > 由于插件中内置的翻译表只包含原版内容的翻译, 故所有模组内容都会提示缺少本地化语言. 目前没有工具能合并模组中的本地化到Prism内置的翻译表中.
> > 这些内容会以英文的形式被查询到.
> 
> 但这次其遍历时将其压缩至一起 启动时间有所加快 因此如标题那样 可能是无关紧要的?

如果不在意这些内容的汉化, 无关紧要. 之前会造成启动时间问题是因为服务端需要等待所有控制台消息一行一行打印出来.
