### ISSUE TITLE
[BUG] 捡拾、存取物品时的错误

### ISSUE THREAD

**Issue by YKDZ** [Rothes/PrismRefracted#4]
**Describe the bug**
https://mcpaste.com/90eb0530453e680a736f85a21b8d7f79
当从地面捡起物品或从箱子拿取物品时会出现此警告

**To Reproduce**
（打开所有物品相关的检查）

**Server (please complete the following information):**
  - Prism Version: 3.7.0-CN-b2
  - Server Type: Purpur
  - Server Version: 1.19.4

**Comment by Rothes** [comment]
你的物品中含有utfmb3不支持的字符，需要修改extra_data表的字符集为utfmb4

**Comment by YKDZ** [comment]
修改后解决
