### ISSUE TITLE
[FEATURE] English version

### ISSUE THREAD

**Issue by szyha** [Rothes/PrismRefracted#5]
**Is your feature request related to a problem? Please describe.**
Many people are not familiar with the Chinese language.

**Describe the solution you'd like**
I wish there was an option to set the English version.

**Describe alternatives you've considered**
Rather, there is no alternative except to learn Chinese. 😆

**Comment by Rothes** [comment]
Sadly I have no plans for platforms other than Chinese right now.
Since most of the strings are hardcoded, adding an English option requires some changes, however, you can still merge all the PRs I created. All changes except Chinese are there.
