### ISSUE TITLE
[BUG?] Fireball from Ghast is detected as "unknown"

### ISSUE THREAD

**Issue by szyha** [Rothes/PrismRefracted#6]
**Describe the bug**
As in the title fireball from Ghast is detected as "unknown".

**To Reproduce**
1. Ghast attacks the player with a fireball.
2. Admin checks the area with commands.

**Expected behavior**
Instead of "unknown," it should be "ghast".

**Screenshots**
![javaw_uVEsJfHD12](https://github.com/Rothes/PrismRefracted/assets/12976368/3bf15b8d-f79a-47ca-b3ff-dbaee36b1c4a)

**Server (please complete the following information):**
  - Prism Version: 3.7.0-CN-b2
  - Server Type: Purpur
  - Server Version: git-Purpur-2004 (MC: 1.20.1)
  
  **Additional context**
The same error is also in the English version.

**Comment by Rothes** [comment]
Fixed on https://github.com/Rothes/PrismRefracted/commit/8aa516e3092587c87fc410600136f176b8ced479

**Comment by Rothes** [comment]
No problem. Now the name recorded seems redundant, may need improvement
