### ISSUE TITLE
[FEATURE]查询时的消息 悬浮显示物品及点击悬浮物品信息时是获取该物品而非传送

### ISSUE THREAD

**Issue by bilwjjsai0093** [Rothes/PrismRefracted#9]
可否引入https://github.com/BananaPuncher714/NBTEditor 实现多版本的nms获取，然后将ItemStack悬浮显示到查询信息中
并且设定点击是获取这个物品，而不是传送(当然,如果不是点的物品的位置,依旧是传送),这在给玩家找回物品时会方便很多

**Comment by Rothes** [comment]
预计在近期测试版发布前添加

**Comment by Rothes** [comment]
已支持 ba94d66a330a71cfdf4f4dc5ca85a02adab2886a
